project:
  type: book
  output-dir: docs
 
book:
  title: "Vignettes to Embrace Uncertainty"
  subtitle: "Linear Mixed Models with Julia"
  author: "Reinhold Kliegl"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - contrasts_kwdyz11.qmd
    - contrasts_fggk21.qmd
    - kwdyz11.qmd
    - kkl15.qmd
execute-dir: project

bibliography: references.bib
csl: apa-annotated-bibliography.csl

format:
  html:
    theme: cosmo

jupyter: julia-1.8
